### ISSUE TITLE
Error during installation using Homebrew

### ISSUE THREAD

**Issue by maksym-mikheienko** [graalvm/homebrew-tap#13]
```
$ brew cask install graalvm/tap/graalvm-ce-java8
==> Caveats
Installing GraalVM CE (Java 8) in /Library/Java/JavaVirtualMachines requires root permissions.
You may be asked to enter your password to proceed.

To use GraalVM CE, you may want to change your `JAVA_HOME`:
  export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.1/Contents/Home

or you may want to add its `bin` directory to your `PATH`:
  export PATH=/Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.1/Contents/Home/bin:"$PATH"

GraalVM CE is licensed under the GPL 2 with Classpath exception:
  https://github.com/oracle/graal/blob/master/LICENSE

==> Downloading https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java8-darwin-amd64-19.3.1.tar.gz
Already downloaded: /Users/XXX/Library/Caches/Homebrew/downloads/315bbd1a34ade636e342238363857bbb528e9d188fe3c89e01717dcd162ce87e--graalvm-ce-java8-darwin-amd64-19.3.1.tar.gz
==> Verifying SHA-256 checksum for Cask 'graalvm-ce-java8'.
==> Installing Cask graalvm-ce-java8
==> Purging files for version 19.3.1 of Cask graalvm-ce-java8
Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/graalvm-ce-java8
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:200:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/pathname.rb:578:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:122:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:143:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:193:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by YarekTyshchenko** [comment]
Seems to install fine for me. Have you tried latest formula?

**Comment by fniephaus** [comment]
Please try again with the latest formula.

**Comment by maksym-mikheienko** [comment]
Sorry guys, it was a problem with my local Cask. Fixed with
`
sudo chown -R $(whoami):staff /usr/local/Caskroom
`
After it installation passed successfully.

**Comment by fniephaus** [comment]
Glad to hear it's working now!
